--- List of all symbols: { Symbol, Equivalent, Type }
---@type string[][]
local symbols = {
    -- Subscript
    { "₀", "0", "subscript" },
    { "₁", "1", "subscript" },
    { "₂", "2", "subscript" },
    { "₃", "3", "subscript" },
    { "₄", "4", "subscript" },
    { "₅", "5", "subscript" },
    { "₆", "6", "subscript" },
    { "₇", "7", "subscript" },
    { "₈", "8", "subscript" },
    { "₉", "9", "subscript" },
    { "ₐ", "a", "subscript" },
    { "ₑ", "e", "subscript" },
    { "ₕ", "h", "subscript" },
    { "ᵢ", "i", "subscript" },
    { "ⱼ", "j", "subscript" },
    { "ₖ", "k", "subscript" },
    { "ₗ", "l", "subscript" },
    { "ₘ", "m", "subscript" },
    { "ₙ", "n", "subscript" },
    { "ₒ", "o", "subscript" },
    { "ₚ", "p", "subscript" },
    { "ᵣ", "r", "subscript" },
    { "ₛ", "s", "subscript" },
    { "ₜ", "t", "subscript" },
    { "ᵤ", "u", "subscript" },
    { "ᵥ", "v", "subscript" },
    { "ₓ", "x", "subscript" },
    { "₊", "+", "subscript" },
    { "₋", "-", "subscript" },
    { "₍", "(", "subscript" },
    { "₎", ")", "subscript" },
    { "₌", "=", "subscript" },

    -- Superscript
    { "⁰", "0", "superscript" },
    { "¹", "1", "superscript" },
    { "²", "2", "superscript" },
    { "³", "3", "superscript" },
    { "⁴", "4", "superscript" },
    { "⁵", "5", "superscript" },
    { "⁶", "6", "superscript" },
    { "⁷", "7", "superscript" },
    { "⁸", "8", "superscript" },
    { "⁹", "9", "superscript" },
    { "ᵃ", "a", "superscript" },
    { "ᵇ", "b", "superscript" },
    { "ᶜ", "c", "superscript" },
    { "ᵈ", "d", "superscript" },
    { "ᵉ", "e", "superscript" },
    { "ᶠ", "f", "superscript" },
    { "ᵍ", "g", "superscript" },
    { "ʰ", "h", "superscript" },
    { "ⁱ", "i", "superscript" },
    { "ʲ", "j", "superscript" },
    { "ᵏ", "k", "superscript" },
    { "ˡ", "l", "superscript" },
    { "ᵐ", "m", "superscript" },
    { "ⁿ", "n", "superscript" },
    { "ᵒ", "o", "superscript" },
    { "ᵖ", "p", "superscript" },
    { "ʳ", "r", "superscript" },
    { "ˢ", "s", "superscript" },
    { "ᵗ", "t", "superscript" },
    { "ᵘ", "u", "superscript" },
    { "ᵛ", "v", "superscript" },
    { "ʷ", "w", "superscript" },
    { "ˣ", "x", "superscript" },
    { "ʸ", "y", "superscript" },
    { "ᶻ", "z", "superscript" },
    { "⁺", "+", "superscript" },
    { "⁻", "-", "superscript" },
    { "⁽", "(", "superscript" },
    { "⁾", ")", "superscript" },
    { "˙", ".", "superscript" },
}

return symbols
